### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [iandreafc/distinctiveness-centrality#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.14. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary distinctiveness -w /tmp/ext distinctiveness==0.14
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting distinctiveness==0.14
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/4f7/5e61c213da37f/distinctiveness-0.14.tar.gz (4.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-h7jefj6t/distinctiveness/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-h7jefj6t/distinctiveness/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-h7jefj6t/distinctiveness/pip-egg-info
         cwd: /tmp/pip-wheel-h7jefj6t/distinctiveness/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-h7jefj6t/distinctiveness/setup.py", line 3, in <module>
        with open("Pypi.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'Pypi.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by iandreafc** [comment]
Thanks I was not aware of the error! Will it be sufficient to add the file in your commit to solve the issue? I will just try that, please let me know if it is solved.
PS
Will update the package on Pypi tomorrow probably, as I need to make another edit.

**Comment by thatch** [comment]
Yes, the PR should be enough to fix this.  The log included there shows building sdist, then building a wheel from that.

**Comment by iandreafc** [comment]
Thanks. Just fixed it. It would be great if you could let me know if it works now.

**Comment by thatch** [comment]
Yes, my script that initially found the problem succeeds with 0.14.1
